### ISSUE TITLE
failed to build doc

### ISSUE THREAD

**Issue by jichenjc** [openmainframeproject/python-zvm-sdk#314]
```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cloudlib4zvm/envs/latest/lib/python2.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension ext.restapi_parameters (exception: No module named yaml)

Extension error:
Could not import extension ext.restapi_parameters (exception: No module named yaml)
```

build doc failed due to yaml not found ,this is caused by commit 
612b8556cb219cf21456177e48c8b053fa9a0a5e

**Comment by jichenjc** [comment]
https://github.com/openmainframeproject/python-zvm-sdk/pull/316 fixed here
